#!/bin/bash

FORMULA_DIR=$(dirname $0)
ARG0=${0##*/}

if [[ -e $FORMULA_DIR/glance-common ]] ; then
  . $FORMULA_DIR/glance-common
else
  echo "ERROR: Could nto load glance-common from $FORMULA_DIR"
fi

function install_hook {
  ensemble-log "Installing nova packages"
  apt-get -y install python-software-properties || exit 1
  add-apt-repository ppa:nova-core/trunk || exit 1
  apt-get update || exit 1
  apt-get -y install glance || exit 1

  glance_ctl all stop

  # work around LP #784837 until its fixed.
  [[ ! -d /var/log/glance ]] && mkdir /var/log/glance
  chown glance /var/log/glance
  [[ ! -e /var/log/glance/api.log ]] && touch /var/log/glance/api.log
  [[ ! -e /var/log/glance/registry.log ]] && touch /var/log/glance/registry.log
  chown glance /var/log/glance/*.log

  # XXX turn up the logging for now.
  set_or_update verbose True api
  set_or_update debug True api
  set_or_update verbose True registry
  set_or_update debug True registry

}

function db_joined {
  ensemble-log "glance: db_joined: requesting access to $NOVA_DB for $DB_USER@$IP"
  echo "DB JOINED $NOVA_DB $DB_USER $HOSTNAME $IP" >>/tmp/log
  relation-set database=$NOVA_DB
  relation-set username=$DB_USER
  relation-set hostname=`uname -n`
  relation-set ip=$IP
  echo "###### DB JOINED $NOVA_DB $DB_USER $HOSTNAME $IP" >>/tmp/log
}

function db_changed {
  DB_HOST=`relation-get db_host`
  DB_PASSWORD=`relation-get password`
  echo "OUT: $DB_HOST $DB_PASSWORD" >>/tmp/log
  if [[ -z $DB_HOST ]] || [[ -z $DB_PASSWORD ]] ; then
    echo "db_changed: DB_HOST || DB_PASSWORD not yet set. Exit 0 and retry"
    exit 0
  else
    echo "db_chan ged: Received password from $DB_HOST"
  fi
  ensemble-log "glance: db_changed: Configuring registry for access to $NOVA_DB@$DB_HOST"
  set_or_update sql_connection "mysql://$DB_USER:$DB_PASSWORD@$DB_HOST/$NOVA_DB" registry
  echo "####### DB CHANGED $DB_HOST $DB_PASSWORD" >>/tmp/log
}

case $ARG0 in
  "start"|"stop") exit 0 ;;
  "install") install_hook ;;
  "shared-db-realtion-joined") db_joined ;;
  "shared-db-relation-changed") db_changed;;
esac

